name: release
on:
  push:
    # Enable when testing release infrastructure on a branch.
    branches:
    - build
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  create-release:
    name: create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install meson
        run: pip install meson ninja
      - name: Meson setup
        run: meson setup builddir/
      - name: Create source distribution
        # no unit tests yet
        run: meson dist -C builddir/ --no-tests
      - name: Create release note
        run: tools/extract_release_note.py NEWS ${{ github.workspace }}-release-note.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: builddir/meson-dist/*
          body_path: ${{ github.workspace }}-release-note.txt

